'Thương hiệu sản phẩm — TDT Studio.\n\nShort code ``tdt`` dùng cho temp / Local AppData / env.\nRoaming user-data vẫn ``VideoToolsProDev`` để không mất preset cũ.\n'
from __future__ import annotations
APP_DISPLAY_NAME = 'TDT Studio'
APP_DISPLAY_NAME_UPPER = 'TDT STUDIO'
APP_TAGLINE = 'Trung tâm làm video'
APP_SHORT = 'tdt'
APP_SHORT_UPPER = 'TDT'
TEMP_PREFIX = 'tdt_'
LOCAL_BRAND_DIR = 'TDT'
USER_DATA_DIR_NAME = 'VideoToolsProDev'
ENV_AI_THREADS = 'TDT_AI_THREADS'
ENV_AI_THREADS_LEGACY = 'VINHKA_AI_THREADS'